services:
  market-data:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: your_database_name
    volumes:
      # Init script mounts here and will run on first startup
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      # Persistent data volume
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
