# Market Data Service Configuration

# Server configuration
server:
  port: 8080
  host: "0.0.0.0"

# Database configuration
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your_password_here"
  dbname: "trading_db"
  sslmode: "disable"
  max_connections: 10
  connection_timeout: 5 # seconds

# Logging configuration
logging:
  level: "debug" # debug, info, warn, error
  format: "console" # json, console
  output: "stdout" # stdout, file
  file_path: "logs/market-data.log" # only used if output is file

# Migrations configuration
migrations:
  enabled: true
  path: "db/migrations"

# Yahoo Finance API configuration
yahoo_finance:
  base_url: "https://query1.finance.yahoo.com/v8/finance/chart/"
  request_timeout: 10 # seconds
  retry_count: 3
  retry_wait_time: 500 # milliseconds
  default_symbols: ["AAPL", "MSFT", "GOOG", "AMZN", "META"]
  update_interval: 15 # minutes
  enable_auto_update: true
