# Market Data Service Configuration

# Server configuration
server:
  port: 8080
  host: "0.0.0.0"

# Database configuration
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your_password_here"
  dbname: "trading_db"
  sslmode: "disable"
  max_connections: 10
  connection_timeout: 5 # seconds

# Logging configuration
logging:
  level: "info" # debug, info, warn, error
  format: "console" # json, console
  output: "stdout" # stdout, file
  file_path: "logs/market-data.log" # only used if output is file

# Migrations configuration
migrations:
  enabled: true
  path: "db/migrations"
